# Copyright (C) 2008 The Android Open-Source Project
# Copyright (C) 2013 OmniROM Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file is the device-specific product definition file for P1C (SCH-I800/SPH-P100) devices. 
# It lists all the overlays, files, modules and properties that are specific 
# to this hardware: i.e. those are device-specific drivers, configuration 
# files, settings, etc...
#
# Note that P1C is not a fully open device. Some of the drivers aren't publicly
# available, which means that some of the hardware capabilities aren't present 
# in builds where those drivers aren't available. Such cases are handled by having
# the configuration separated into two halves: this half here contains the parts
# that are available to everyone, while another half in the vendor/ hierarchy 
# augments that set with the parts that are only relevant when all the associated
# drivers are available. Aspects that are irrelevant but harmless in no-driver
# builds should be kept here for simplicity and transparency. 

# Device specific configuration
# This is the hardware-specific overlay, which points to the location
# of hardware-specific resource overrides, typically the frameworks and
# application settings that are stored in resourced.
DEVICE_PACKAGE_OVERLAYS := device/samsung/p1c/overlay

# Inherit device configuration common between GSM & CDMA products.
$(call inherit-product, device/samsung/p1-common/device_base.mk)

# Inherit VENDOR blobs and configuration.
# There are two variants of the half that deals with the unavailable drivers: one
# is directly checked into the unreleased vendor tree and is used by engineers who
# have access to it. The other is generated by setup-makefile.sh in the same
# directory as this files, and is used by people who have access to binary versions 
# of the drivers but not to the original vendor tree. Be sure to update both.
$(call inherit-product-if-exists, vendor/samsung/p1c/p1c-vendor.mk)

# Inherit from other products - most specific first
$(call inherit-product, $(SRC_TARGET_DIR)/product/full.mk)
$(call inherit-product, $(SRC_TARGET_DIR)/product/languages_full.mk)

# Init files
PRODUCT_COPY_FILES += \
    device/samsung/p1c/rootdir/init.p1c.rc:root/init.p1c.rc \
    device/samsung/p1c/rootdir/ueventd.p1c.rc:root/ueventd.p1c.rc \
    device/samsung/p1c/rootdir/init.p1c.usb.rc:root/init.p1c.usb.rc \
    device/samsung/p1c/rootdir/init.p1c.usb.rc:recovery/root/usb.rc \
    device/samsung/p1-common/rootdir/init.recovery.rc:root/init.recovery.p1c.rc \
    device/samsung/p1c/fstab.p1c:root/fstab.p1c \
    device/samsung/p1c/twrp.fstab:root/etc/twrp.fstab

# RIL
PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.telephony.cdma.xml:system/etc/permissions/android.hardware.telephony.cdma.xml \
    device/samsung/p1c/prebuilt/etc/ppp/ip-up:system/etc/ppp/ip-up

# Verizon cdma stuff
PRODUCT_PROPERTY_OVERRIDES += \
       ro.telephony.default_network=4 \
       ro.ril.def.agps.mode=2 \
       ro.ril.samsung_cdma=true \
       ro.cdma.home.operator.numeric=310004 \
       ro.cdma.home.operator.alpha=VzW \
       ro.cdma.homesystem=64,65,76,77,78,79,80,81,82,83 \
       ro.cdma.data_retry_config=default_randomization=2000,0,0,120000,180000,540000,960000 \
       ro.cdma.otaspnumschema=SELC,3,00,07,80,87,88,99 \
       net.cdma.pppd.authtype=require-chap \
       net.cdma.pppd.user=user[SPACE]VerizonWireless \
       net.cdma.datalinkinterface=/dev/ttyCDMA0 \
       net.cdma.ppp.interface=ppp0 \
       net.connectivity.type=CDMA1 \
       net.interfaces.defaultroute=cdma \
       rild.libpath=/system/lib/libsec-ril40.so \
       rild.libargs=-d/dev/ttyS0 \
       mobiledata.interfaces=wlan0,ppp0

# Set here product definitions that valid for all p1 products
PRODUCT_BRAND := Samsung
PRODUCT_MANUFACTURER := Samsung

#Set build fingerprint / ID / Product Name ect.
PRODUCT_BUILD_PROP_OVERRIDES +=
       PRODUCT_NAME=SCH-I800 \
       TARGET_DEVICE=SCH-I800 \
       BUILD_FINGERPRINT=verizon/SCH-I800/SCH-I800:2.3.4/GINGERBREAD/EF01:user/release-keys \
       PRIVATE_BUILD_DESC="SCH-I800-user 2.3.4 GINGERBREAD EF01 release-keys"
